version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
    - location: start_server
      timeout: 300
      runas: root
 permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
